---
- name: SR Linux | Hostname alanini bul
  hosts: nokia_srlinux
  gather_facts: false

  tasks:
    - name: Candidate path'leri dene (state)
      nokia.srlinux.get:
        paths:
          - { path: /system, datastore: state }
          - { path: /system/information, datastore: state }
          - { path: /system/information/host-name, datastore: state }
          - { path: /system/information/hostname, datastore: state }
          - { path: /system/name/host-name, datastore: state }
      register: out
      ignore_errors: true

    - name: Sonucu yazdir
      ansible.builtin.debug:
        var: out
