#============ Bu kod ne yapar=============#
# Play bookları sırayla çağırır.
# Sadece orkestrasyon amacıyla kullanılır.
#=========================================#
---
- import_playbook: interfaces.yml
  tags:
    - interfaces

- import_playbook: routing.yml
  tags:
    - routing

- import_playbook: verify.yml
  tags:
    - verify