---
- name: Precheck | Inventory ve grup kontrol√º
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Host bilgisi yazdir
      ansible.builtin.debug:
        msg:
          - "HOST: {{ inventory_hostname }}"
          - "GROUPLAR: {{ group_names }}"
          - "ENV: local connection"