---
- name: SR Linux - Full Run
  hosts: srl
  gather_facts: false
  roles:
    - srl_common
    - srl_system
    - srl_interfaces
    - srl_lag
    - srl_vlan
    - srl_underlay_isis
    - srl_verify