- name: SR Linux | JSON-RPC version retrieval test
  hosts: nokia_srlinux
  gather_facts: false
  tasks:
    - name: Get SR Linux software version
      nokia.srlinux.get:
        paths:
          - path: /system/information/version
            datastore: state
      register: out

    - name: Display version information
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} -> {{ out.result[0] }}"
